
from read_and_save_cifar_data.cfar10_main import cfar10_read_save_locally_numpy_csv
from read_and_save_cifar_data.cfar100_main import cfar100_read_save_locally_numpy_csv

from preprocess.our_data.our_data_main import main

from preprocess.additional_operations.normalization import standardize_data
from preprocess.additional_operations.merge_npz_files import merge
from preprocess.additional_operations.divideToTrainAndTest import divide_train_test

cfar10_read_save_locally_numpy_csv()
cfar100_read_save_locally_numpy_csv()

main()


standardize_data()
merge()
divide_train_test()